### ISSUE TITLE
Example in README of How to Modify UI

### ISSUE THREAD

**Issue by kerns** [dromru/react-photoswipe-gallery#1038]
Would really like an example in the README of how to modify the UI. I want to set...

```
arrowPrev: false,
arrowNext: false,
zoom: false,
close: false,
counter: false
```
...without hiding them via CSS.

https://photoswipe.com/styling/

**Comment by kerns** [comment]
Would be great if it was as simple as `<Gallery close="false">` but that isn't working for me :)

**Comment by akhmadullin** [comment]
Hi

You can modify [PhotoSwipe options](https://photoswipe.com/options/) via `options` [prop](https://github.com/dromru/react-photoswipe-gallery#gallery) of `Gallery` component

```js
import { Gallery } from 'react-photoswipe-gallery'

...

<Gallery 
  options={{
    arrowPrev: false,
    arrowNext: false,
    zoom: false,
    close: false,
    counter: false,
  }}
>
 ...
</Gallery>
```

**Comment by akhmadullin** [comment]
Now you can find example of how to modify UI in [photoswipe customization section of README](https://github.com/dromru/react-photoswipe-gallery#photoswipe-customization)
