### ISSUE TITLE
v3 isn't detecting `ref` prop being passed in

### ISSUE THREAD

**Issue by EvHaus** [dromru/react-photoswipe-gallery#1317]
**Describe the bug**

After upgrading to v3.0.0, the component isn't working for me anymore and is throwing:

```
item.js:36 Uncaught Error: 
    
    No valid `ref` provided.
    You should use `ref` from render prop of Item component.
    Example:
    <Item>{({ ref }) => <div ref={ref}></div>}</Item>
```

**To Reproduce**

My code is as follows:

```tsx
import 'photoswipe/dist/photoswipe.css';
import {Gallery, Item} from 'react-photoswipe-gallery';
import Image from 'next/image';

<Gallery>
	<div className={styles.gallery}>
		{Array.from(new Array(8)).map((_, i) => {
			const src = `/images/myimage-${i + 1}.jpg`;

			return (
				<Item
					height='768'
					key={src}
					original={src}
					thumbnail={src}
					width='1024'>
					{({ref, open}) => (
						<div
							className={styles.thumbnail}
							ref={ref}>
							<Image
								alt={`My image ${i}`}
								height={140}
								onClick={open}
								src={src}
								width={200} />
						</div>
					)}
				</Item>
			);
		})}
	</div>
</Gallery>
```

I don't understand what's wrong. The `ref` is being passed in...

**Expected behavior**
This works just fine in `v2.2.7` but fails in `v3.0.0`.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 119.0.6045.200

**Smartphone (please complete the following information):**

**Additional context**

**Comment by EvHaus** [comment]
Yup, @MaximKondratev is absolutely correct. Turning off strict mode makes the issue go away.

**Comment by hatem-72** [comment]
We had a similar issue a few weeks ago with another package: https://github.com/jscottsmith/react-scroll-parallax/issues/233

**Comment by Bernardo-ive** [comment]
I can confirm the issue is as described, not useing next just a plain CRA.
 is there a fix planned?

**Comment by MaximKondratev** [comment]
Don't have time to dig in for now. Interesting thing is that I could not reproduce it with strict mode enabled on my work project.

**Comment by MaximKondratev** [comment]
Actually I will try to find the problem today. I was sure it is about next, but since @Bernardo-ive said it is in CRA it should be easier to locate the problem

**Comment by MaximKondratev** [comment]
Look like this old issue is related https://github.com/facebook/react/issues/24670. I have a quick fix, but it feels wrong

**Comment by MaximKondratev** [comment]
I have released v3.0.1. @Bernardo-ive @EvHaus could you pls check if it resolves the issue?

**Comment by EvHaus** [comment]
Yup, 3.0.1 works great for me. Thanks!

**Comment by Bernardo-ive** [comment]
Yeah, 3.0.1 fixes it, thanks for action on this!
