### ISSUE TITLE
Text in the readme about Photoswipe V1 and V4 is confusing

### ISSUE THREAD

**Issue by looeee** [dromru/react-photoswipe-gallery#1446]
The text that says to use Photoswipe V1 instead of V1 seems to be out of date. 

> A configurable and flexible React component wrapper around [PhotoSwipe](https://photoswipe.com/). ℹ️ If you are using PhotoSwipe v4, Use [v1](https://github.com/dromru/react-photoswipe-gallery/tree/v1.3.10) instead

The package.json currently installs photoswipe v5.4.3

**Comment by akhmadullin** [comment]
@looeee, if you need photoswipe v4, you should use react-photoswipe-gallery v1

try to install dependencies in this way:

```
yarn add photoswipe@4 react-photoswipe-gallery@1.3.10
```

or

```
npm install photoswipe@4 react-photoswipe-gallery@1.3.10 --save
```

**Comment by looeee** [comment]
OK, that makes sense. Thank you.  

However, I still think the text is confusing. I read it as:

> If you are using PhotoSwipe v4, that's a mistake and you should be using _PhotoSwipe_ v1 instead. 

Whereas what you mean is:

> If you want to use the old PhotoSwipe v4 then you should use the v1 of _this_ library

**Comment by akhmadullin** [comment]
@looeee, I've updated docs in [readme](https://github.com/dromru/react-photoswipe-gallery/blob/master/README.md), hope it become more obvious

**Comment by looeee** [comment]
That's much clearer, thank you :)
