### ISSUE TITLE
To add slides after PhotoSwipe is opened

### ISSUE THREAD

**Issue by sandeepk9635** [dromru/react-photoswipe-gallery#511]
When my items update inside gallery when gallery is opened? How can i update my gallery so that i can slide through next slides? Is there and update function to call?

**Comment by irudoy** [comment]
You can do it with [PhotoSwipe API](https://photoswipe.com/documentation/api.html) (take a look at `gettingData` event and `Adding slides dynamically` section of the docs). Use [onOpen](https://github.com/dromru/react-photoswipe-gallery#gallery) prop to access it.

**Comment by sandeepk9635** [comment]
I want to push items when im in middle of slideshow not onOpen? how can i do that? please help !!
