### ISSUE TITLE
Support PhotoSwipe v5

### ISSUE THREAD

**Issue by irudoy** [dromru/react-photoswipe-gallery#591]
Preparing to forthcoming PhotoSwipe v5 release https://github.com/dimsemenov/PhotoSwipe/issues/1749.
It was fully rewritten and some initialization-relative concepts have changed.

* react-photoswipe-gallery v2.x should get rid of CustomGallery and support only PhotoSwipe >=v5
* react-photoswipe-gallery v1.x will support PhotoSwipe <=v4

What should be done:
- [x] add new props for Item component (cropped, srcset, etc.)
- [x] decide what to do with removed features like HistoryAPI/captions
- [x] implement PhotoSwipeLightbox functionality (pointerPos, global check, destroy on unmount)

**Comment by Perni1984** [comment]
@irudoy we are planning to use PhotoSwipe v5 in our next.js based website. Is the v5 branch already usable, or can we contribute here to get it useable?

**Comment by irudoy** [comment]
@Perni1984 I would not recommend using v5 in production while [dimsemenov/PhotoSwipe v5](https://github.com/dimsemenov/PhotoSwipe) is in the beta stage. [dromru/react-photoswipe-gallery/tree/photoswipe-v5](https://github.com/dromru/react-photoswipe-gallery/tree/photoswipe-v5) is definitely not ready yet, even though it works in general. Anyway, you can give it a try with `yarn add photoswipe@dimsemenov/photoswipe#v5-beta react-photoswipe-gallery@next`, if you like adventures :) But API definitely will change slightly.
