### ISSUE TITLE
Is there a way to get uncropped images

### ISSUE THREAD

**Issue by Riyaz-01** [dromru/react-photoswipe-gallery#681]
**Describe the bug**
I want to view uncropped images in my gallery. I tried to achieve that by not passing height and width prop to <Item><Item/> component but it gives the following error.
TypeError: Cannot read properties of undefined (reading 'x').

**To Reproduce**
Just remove width and height props from <Item/> component.

**Comment by irudoy** [comment]
According to the PhotoSwipe [documentation](https://photoswipe.com/documentation/faq.html#image-size), it requires image width and height and can't work reliably without those.

We definitely need better error reporting when dimensions weren't provided.

**Comment by Manubi** [comment]
I have the same problem with portrait and landscape images.

How do you change between landscape and portrait mode?
Thanks

**Comment by irudoy** [comment]
@Manubi doesn't clearly understand what exact problem are you experiencing? Can you reproduce it [here](https://dromru.github.io/react-photoswipe-gallery/iframe.html?id=gallery--simple&args=&viewMode=story)?

PhotoSwipe core does well with images in any orientation when dimensions are provided.
