### ISSUE TITLE
Any plans for adding thumbnails to the modal view?

### ISSUE THREAD

**Issue by guillermo-avalos** [dromru/react-photoswipe-gallery#748]
I think it'd be a nice addition to have a row of thumbnails for the rest of the images within the same `Gallery`. Any plans for it?

**Comment by irudoy** [comment]
You can do it this way now: https://dromru.github.io/react-photoswipe-gallery/?path=/story/demo-custom-ui-elements--thumbnails-in-opened-photoswipe

**Comment by guillermo-avalos** [comment]
Thank you! Tried to replicate it within my jsx file and got a ton of errors though.

**Comment by irudoy** [comment]
Do you using the latest version of react-photoswipe-gallery and photoswipe?

**Comment by guillermo-avalos** [comment]
Photoswipe is 5.2.4 and react-photoswipe-gallery is 2.0.1

The error I’m getting in the console is:

Warning: Unknown event handler property `onBeforeOpen`. It will be ignored.


I did have to change line 40 from:
e.target as HTMLImageElement | HTMLDivElement

To:
e.target

And line 9 from:
onBeforeOpen: GalleryProps['onBeforeOpen'] = (instance)

To:
onBeforeOpen = (instance)

Otherwise it wouldn’t compile at all.

**Comment by akhmadullin** [comment]
@guillermo-avalos, https://dromru.github.io/react-photoswipe-gallery/?path=/story/demo-custom-ui-elements--thumbnails-in-opened-photoswipe example is written in TypeScript.

According to errors, that you provided, you use JavaScript - that’s why type annotations does not work and errors appear.

It’s ok. Just remove type annotations from example and everything should work in JavaScript environment.

**Comment by guillermo-avalos** [comment]
Thanks for all your help. I saw that it was written in TypeScript and removed all annotations, but I’m still getting the same error. It’s weird. The script compiles, but “unknown event handler” still shows up.

**Comment by akhmadullin** [comment]
Can you provide us with your code sample, so we be able to reproduce this error?

It can be codepen, GitHub repo or just code sample in comment right there.

**Comment by guillermo-avalos** [comment]
Sure, not doing anything complex. Here's the Gallery code. For some context, I'm mapping through an array of images coming from a Sanity backend. All styling was done with TailwindCSS. If you want to see it live, it's available [here](https://magnayachts.netlify.app/en/second-hands/sunseeker-predator-58)

The `onBeforeOpen={onBeforeOpen}` prop in `Gallery` is what's triggering the error in the console.

```
<Gallery shareButton={false} fullscreenButton={false} onBeforeOpen={onBeforeOpen}>

{/* Map through each individual photo in the `galleryImages` array and create an `Item` for each one using the `assetId`, URLs and dimensions */}
 {pageContent.galleryImages.map(
   (galleryImage) => (
     /* Since there's gap of 1 in the container, 50% causes wrapping so set it to 49% */
     <li
    key={galleryImage.asset.assetId}
    className="h-40 w-[49%] snap-center hover:brightness-75 sm:w-[32%] md:w-[24%]"
    >
               <Item
                   original={urlFor(galleryImage).format('webp').quality(95).url()}
                   thumbnail={urlFor(galleryImage).format('webp').size(400).url()}
                   width={galleryImageInt.asset.dimensions.width}
                   height={galleryImageInt.asset.dimensions.height}
              >
                  {({ ref, open }) => (
                       <img
                          ref={ref}
                          onClick={open}
                          src={urlFor(galleryImage).format('webp').size(400).url()}
                          className="h-full w-full cursor-pointer object-cover"
                      />
                  )}
               </Item>
  </li>
 )
)}
</Gallery>
```

And the un-TypeScripted code:

```
const onBeforeOpen = instance => {
  instance.on("uiRegister", () => {
    instance.ui.registerElement({
      name: "bulletsIndicator",
      order: 9,
      isButton: false,
      appendTo: "wrapper",
      onInit: (el, pswpInstance) => {
        let prevIndex = -1
        const thumbnails = []

        el.style.position = "absolute"
        el.style.bottom = "20px"
        el.style.left = "10px"
        el.style.right = "0"
        el.style.display = "grid"
        el.style.gridGap = "10px"
        el.style.gridTemplateColumns = "repeat(auto-fit, 40px)"
        el.style.gridTemplateRows = "repeat(auto-fit, 40px)"
        el.style.justifyContent = "center"

        for (let i = 0; i < pswpInstance.options.dataSource.length; i++) {
          const slideData = pswpInstance.options.dataSource[i]

          const thumbnail = document.createElement("div")
          thumbnail.style.transition = "transform 0.15s ease-in"
          thumbnail.style.opacity = "0.6"
          thumbnail.style.cursor = "pointer"
          thumbnail.onclick = e => {
            const target = e.target
            const thumbnailEl =
              target.tagName === "IMG" ? target.parentElement : e.target
            pswpInstance.goTo(thumbnails.indexOf(thumbnailEl))
          }

          const thumbnailImage = document.createElement("img")
          thumbnailImage.setAttribute("src", slideData.msrc)
          thumbnailImage.style.width = "100%"
          thumbnailImage.style.height = "100%"
          thumbnailImage.style.objectFit = "cover"

          thumbnail.appendChild(thumbnailImage)

          el.appendChild(thumbnail)

          thumbnails.push(thumbnail)
        }

        instance.on("change", a => {
          if (prevIndex >= 0) {
            const prevThumbnail = thumbnails[prevIndex]
            prevThumbnail.style.opacity = "0.6"
            prevThumbnail.style.cursor = "pointer"
            prevThumbnail.style.transform = "scale(1)"
          }

          const currentThumbnail = thumbnails[pswpInstance.currIndex]
          currentThumbnail.style.opacity = "1"
          currentThumbnail.style.cursor = "unset"
          currentThumbnail.style.transform = "scale(1.2)"

          prevIndex = pswpInstance.currIndex
        })
      }
    })
  })
}
```

**Comment by akhmadullin** [comment]
Are you sure, that you updated `react-photoswipe-gallery` to second version?

> `<Gallery shareButton={false} fullscreenButton={false} onBeforeOpen={onBeforeOpen}>`

In second version there are no `shareButton` and `fullscreenButton` props.

Actual Gallery's prop description you can find [here](https://github.com/dromru/react-photoswipe-gallery#gallery).

Also there are no errors in console of your [app example](https://magnayachts.netlify.app/en/second-hands/sunseeker-predator-58) - does this app include `onBeforeOpen` prop in its code base?

**Comment by guillermo-avalos** [comment]
I'm pretty sure I did.
```
npm update react-photoswipe-gallery                                                                                                ─╯
up to date, audited 182 packages in 4s
```

```
npm view react-photoswipe-gallery version                                                                                          ─╯
2.0.4
```

Oh, and the live version of the site does not currently have the `onBeforeOpen` prop.

**Comment by guillermo-avalos** [comment]
But now I'm guessing there's something wrong, as the `withDownloadButton={false}` prop I tried just now also throws an error in the console. I do have the correct Photoswipe version installed though...
```
npm view photoswipe version                                                                                                            ─╯
5.2.4
```

**Comment by guillermo-avalos** [comment]
I ended up uninstalling both packages and re-installing them. It's working correctly now, it was a npm issue after all. Thanks!
