### ISSUE TITLE
Is it possible to current index when the current slide is changed?

### ISSUE THREAD

**Issue by ugnelis** [dromru/react-photoswipe-gallery#767]
I am trying to combine SwiperJS with react-photoswipe-gallery. I need to get the index of the current slide.

Is it possible to current index when the current slide is changed? If not, is it possible to get when the "next" button is pressed?

**Comment by irudoy** [comment]
Yes! You can use [onOpen](https://github.com/dromru/react-photoswipe-gallery#customgallery) hook to access `photoswipe` instance [(docs for v4)](https://github.com/dimsemenov/PhotoSwipe/blob/v4.1.3/website/documentation/api.md). Seems like `pswp.getCurrentIndex()` is one that you need.

**Comment by ugnelis** [comment]
But how do you trigger every time the `pswp.getCurrentIndex()`? Because in my case, it works only once (when the it opens)

```javascript
...
return (
    <div className={'gallery'}>
      <LightboxGallery
        layoutRef={layoutRef as React.MutableRefObject<any>}
        ui={PhotoswipeUIDefault}
        onOpen={(options) => {
          console.log(options.getCurrentIndex());
        }}
      >
...
```

**Comment by irudoy** [comment]
Look at events: for example `pswp.listen('afterChange', () => {})`

**Comment by ugnelis** [comment]
Understood, thanks!
