### ISSUE TITLE
Is it possible to have a React component as html alternative?

### ISSUE THREAD

**Issue by ugnelis** [dromru/react-photoswipe-gallery#768]
Hi again,

I want to have video support for slides. I tried using ` <LightboxItem html={...}>` but it seems failed. I tried to convert React component into HTML `ReactDOMServer.renderToString(videoPlayer());` but it Reacts throws errors.

Could you share how you would tackle this problem?

**Comment by irudoy** [comment]
It's more relevant to the original PhotoSwipe library rather than this wrapper. As I know, the `html` prop currently works as expected, when you pass a valid html string to it. Anyway, it's quite hard to guess for a reason without isolated reproduction repo

**Comment by irudoy** [comment]
Should be fixed in v2.1.0

https://github.com/dromru/react-photoswipe-gallery#custom-slide-content
