### ISSUE TITLE
Items with dynamic height and width

### ISSUE THREAD

**Issue by guillermo-avalos** [dromru/react-photoswipe-gallery#775]
I'm mapping through an array of images coming for a CMS backend, and they all have different `height` and `width` attributes. How can I avoid image distortion if the `Item` component won't work unless I hardcode those values? All my images are distorted inside the Lightbox. Any ideas?

**Comment by trescomasdev** [comment]
How did you solve this problem?

**Comment by guillermo-avalos** [comment]
I was able to query for the `height` and `width` values for each image directly from my backend.

**Comment by trescomasdev** [comment]
thanks for the quick reply!
