### ISSUE TITLE
Empty slides with custom `content`

### ISSUE THREAD

**Issue by boreyko1** [dromru/react-photoswipe-gallery#837]
**Describe the bug**
Hi! It seems like there is a bug when using custom `content` with React components. Sometimes there are empty slides at random indexes. Unfortunately, I couldn't identify what causes this

**To Reproduce**
Reproduction link – https://stackblitz.com/edit/nextjs-db1zk4?file=pages/index.js.
Both galleries (simple `<img />` tag and a custom React component) have the same bug with missing content

**Expected behavior**
All slides are rendered correctly

**Screenshots**
<details>
  <summary>Empty content in devtools</summary>
  <img width="1440" alt="image" src="https://user-images.githubusercontent.com/32419460/168282150-b35bbdb0-f4d3-4b20-a9bd-c443688b5c87.png">
</details>

**Additional context**
Let me know if I can help somehow. Thanks!

**Comment by irudoy** [comment]
Thanks for reporting and reproduction! Should be fixed in v2.2.1
