### ISSUE TITLE
zoom button

### ISSUE THREAD

**Issue by raoulguillermo** [dromru/react-photoswipe-gallery#933]
Hi!
How can i show the zoombutton in the lightbox?

**Comment by akhmadullin** [comment]
Hi.

Zoom button is shown by default.

https://dromru.github.io/react-photoswipe-gallery/?path=/story/demo-basic--basic

<img width="1687" alt="Снимок экрана 2022-08-31 в 09 10 03" src="https://user-images.githubusercontent.com/37641303/187559320-0b1ffaba-671e-44c9-9723-556cb3337ed7.png">
