### ISSUE TITLE
Custom content not getting events

### ISSUE THREAD

**Issue by tjg184** [dromru/react-photoswipe-gallery#954]
**Is your feature request related to a problem? Please describe.**

With custom content for an `Item`, any input controls are disabled on that content. I'm speculating it has to do with the swipe input or some other event listener. There may be a way around this, but am writing up for any help. This could be a bug too, but I was thinking most of the content here was maybe expected to be just "read-only" type content.   

Example:

On `MyCustomControl`, all events are being passed to the actual gallery and effectively are disabled on the custom content. On this example `MyCustomControl` has a simple input box.  

`<Item {<MyCustomControl photo={ item } /> }`

**Describe the solution you'd like**

Allow events to be passed to the custom content. 

**Describe alternatives you've considered**

I've tried experimenting with several options on the actual `Gallery` instance.

**Comment by irudoy** [comment]
Have you tried calling `e.preventDefault()` in `contentLoad` hook? Take a look at https://photoswipe.com/custom-content/#google-maps-demo

**Comment by Poylar** [comment]
I want to reopen this issue as I encountered the same problem in Safari.
If the custom content is html video, then the functions of rewinding, changing sound, etc. do not work only on safari.
The solution above works, but it also disables half of the gallery functionality, which is not very good.
Are there any other options to leave the swipe and video control functionality in Safari?
